yaoj_judge: main.o afterward.o compare.o style.o compile.o connection.o download.o execute.o log.o daemon.o
	gcc -o 	Judger main.o style.o afterward.o compare.o compile.o connection.o download.o execute.o log.o daemon.o -lm -lmysqlclient -lz

clean:
	rm *.o yaoj_judge
